export enum ClaimStatusType {
    ACTIVE = "ACTIVE",
    FILED = "FILED",
    IN_PROGRESS_DISASTER = "IN_PROGRESS_DISASTER",
    IN_PROGRESS_PERSONAL = "IN_PROGRESS_PERSONAL",
    IN_PROGRESS_BUSINESS = "IN_PROGRESS_BUSINESS",
    IN_PROGRESS_INSURANCE = "IN_PROGRESS_INSURANCE",
    IN_PROGRESS_EXPORT = "IN_PROGRESS_EXPORT", 
}
