services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MODE=${MODE-prod}
    env_file:
      - ./backend/.env 
    ports:
      - "3001:3001"
    volumes:
      - ${LOG_VOLUME_MOUNT:-/app/log}:/app/log
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: ./app
          ignore:
            - log/
    container_name: backend
    networks:
      - app-network
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - MODE=${MODE-prod}
    ports:
      - "3000:3000"
  
networks:
  app-network:
    driver: bridge