import { Hono } from "hono";
import { DataSource } from "typeorm";
import { userRoutes } from "./modules/user/route";
import { setUpOpenApiRoutes } from "./modules/openapi/all-routes";
import { locationAddressRoute } from "./modules/location-address/route";
import { companyRoutes } from "./modules/company/route";
import { disasterRoutes } from "./modules/disaster/route";
import { claimRoutes } from "./modules/claim/route";
import { disasterNotificationRoutes } from "./modules/disasterNotifications/route";
import { quickbooksRoutes } from "./modules/quickbooks/routes";
import { invoiceRoutes } from "./modules/invoice/route";
import { purchaseRoutes } from "./modules/purchase/route";
import { preferenceRoutes } from "./modules/preferences/route";
import { invoiceLineItemsRoutes } from "./modules/invoiceLineItem/route";

export const setUpRoutes = (app: Hono, db: DataSource) => {
    app.route("/users", userRoutes(db));
    app.route("/location-address", locationAddressRoute(db));
    app.route("/companies", companyRoutes(db));
    app.route("/openapi", setUpOpenApiRoutes(db));
    app.route("/disaster", disasterRoutes(db));
    app.route("/claims", claimRoutes(db));
    app.route("/disasterNotification", disasterNotificationRoutes(db));
    app.route("/quickbooks", quickbooksRoutes(db));
    app.route("/quickbooks/invoice", invoiceRoutes(db));
    app.route("/purchase", purchaseRoutes(db));
    app.route("/invoice", invoiceRoutes(db));
    app.route("/notifications", preferenceRoutes(db));
    app.route("/invoice/line", invoiceLineItemsRoutes(db));
};
